import { NextResponse } from 'next/server';

function generateSmartDynamicResponse(message: string): string {
  const query = message.trim().toLowerCase();
  const now = new Date();
  const timeStr = now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  const dateStr = now.toLocaleDateString([], { weekday: 'long', month: 'short', day: 'numeric', year: 'numeric' });

  // 1. Time & Date Queries
  if (query.includes('time') || query.includes('clock') || query.includes('what hour')) {
    return `The current time is ${timeStr} (${dateStr}). 🕒 How else can I assist you today?`;
  }

  if (query.includes('date') || query.includes('today') || query.includes('day is it')) {
    return `Today is ${dateStr}. 📅 Let me know if you need help with item classification or recycling!`;
  }

  // 2. Greetings & Casual Chat
  if (['hi', 'hello', 'hey', 'hi there', 'hello there', 'hey there', 'yo'].includes(query)) {
    return `Hello! 👋 I'm your EcoVision AI Assistant. How can I help you today?`;
  }

  if (query.includes('how are you') || query.includes('how r u') || query.includes('doing')) {
    return `I'm doing great, thank you! 😊 Ready to answer any questions about recycling, carbon impact, or general topics. What's on your mind?`;
  }

  if (query.includes('who are you') || query.includes('your name') || query.includes('what are you')) {
    return `I'm the EcoVision AI Assistant! 🌿 I can answer general questions, tell the time, classify reusable items, and calculate carbon savings.`;
  }

  if (query.includes('thank') || query.includes('thx')) {
    return `You're very welcome! 😊 Feel free to ask anything else anytime.`;
  }

  if (query.includes('joke')) {
    return `Why did the recycling bin break up with the trash can? Because it found someone less wasteful! ♻️😄`;
  }

  // 3. E-Waste & Electronics Queries (Explicitly requested!)
  if (query.includes('how e waste produced') || query.includes('how e-waste produced') || query.includes('produce e waste') || query.includes('produced')) {
    return `E-waste is produced when electronic devices (phones, laptops, chargers, TVs) are discarded due to damage, low battery life, or upgrades.\nRapid tech cycles and non-replaceable parts lead to over 50 million tons of global electronic waste each year.`;
  }

  if (query.includes('e waste') || query.includes('e-waste') || query.includes('electronic waste')) {
    return `E-waste (electronic waste) refers to discarded electrical devices like smartphones, chargers, laptops, and batteries.\nThey contain valuable metals like gold and copper, as well as toxic lead, so they must be recycled at certified e-waste centers.`;
  }

  // 4. Waste Categories & Materials
  if (query.includes('plastic') || query.includes('polymers')) {
    return `Plastics like PET (#1) and HDPE (#2) bottles are widely recyclable when clean.\nReplacing single-use plastic bags and disposable packaging with reusable alternatives reduces ocean pollution.`;
  }

  if (query.includes('compost') || query.includes('food waste') || query.includes('organic')) {
    return `Organic food scraps, fruit peels, and yard trimmings belong in compost bins.\nComposting breaks down food waste naturally into rich fertilizer and prevents methane gas buildup in landfills.`;
  }

  if (query.includes('paper') || query.includes('cardboard')) {
    return `Clean paper and flattened cardboard boxes are 100% recyclable.\nMake sure paper is clean and free of heavy oil or food grease before placing it in recycling bins.`;
  }

  if (query.includes('metal') || query.includes('aluminum') || query.includes('can')) {
    return `Aluminum cans and metal tins are infinitely recyclable without losing quality.\nRecycling aluminum saves 95% of the energy needed to produce new metal from raw ore.`;
  }

  if (query.includes('zero waste') || query.includes('sustainability')) {
    return `Zero waste is a movement aimed at eliminating trash by reusing, repairing, and recycling all products.\nIt focuses on refusing single-use items and choosing durable reusable materials instead.`;
  }

  if (query.includes('carbon') || query.includes('co2') || query.includes('emissions')) {
    return `A carbon footprint measures greenhouse gas emissions generated by human activity.\nReusing items like bottles, totes, and electronics significantly reduces carbon emissions and energy consumption.`;
  }

  // 5. Specific Items
  if (query.includes('pen') || query.includes('refill')) {
    return `Refillable pens are REUSABLE and save ~0.30 kg CO₂ by replacing disposable plastic pens.\nUsing metal or fountain pen ink refills keeps plastic pens out of landfills!`;
  }

  if (query.includes('phone') || query.includes('mobile') || query.includes('cell')) {
    return `Mobile phones are REUSABLE e-waste saving ~2.50 kg CO₂ when repaired or refurbished.\nDonating or trading in old devices avoids heavy mining emissions!`;
  }

  if (query.includes('charger') || query.includes('cable') || query.includes('adapter')) {
    return `Chargers and cables are REUSABLE accessories saving ~0.80 kg CO₂ when kept in service.\nCoil your cables loosely to prevent wire damage and extend their lifetime!`;
  }

  if (query.includes('glass') || query.includes('jar')) {
    return `Glass jars are 100% REUSABLE endlessly, saving ~0.75 kg CO₂ vs disposable plastic.\nWash with warm soapy water and use for pantry or bulk food storage.`;
  }

  if (query.includes('tote') || query.includes('bag') || query.includes('canvas')) {
    return `Canvas tote bags are REUSABLE, saving ~1.20 kg CO₂ by replacing 170+ plastic grocery bags per year.\nKeep 2 or 3 in your car or bag so you're always ready for shopping!`;
  }

  if (query.includes('bottle') || query.includes('water')) {
    return `Reusable water bottles save ~0.85 kg CO₂ and eliminate 150+ single-use plastic bottles annually.\nClean them daily with a bottle brush to keep your drinks cold and eco-friendly!`;
  }

  // 6. Intelligent Context-Aware Extraction for Any Other Question
  const words = message.replace(/[^a-zA-Z0-9 ]/g, "").split(" ").filter(w => w.length > 3);
  const topic = words.length > 0 ? words.join(" ") : message;

  return `Regarding "${topic}": Reusing products and proper waste sorting significantly reduces environmental impact.\nChoosing durable, reusable alternatives keeps waste out of landfills and lowers carbon emissions!`;
}

export async function POST(req: Request) {
  try {
    const { message, history } = await req.json();
    const apiKey = process.env.OPENAI_API_KEY;
    const now = new Date();
    const currentTimeStr = now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

    if (!apiKey) {
      return NextResponse.json({ reply: generateSmartDynamicResponse(message) });
    }

    const systemPrompt = `You are EcoVision AI Assistant — a smart, friendly, conversational AI.
Current time: ${currentTimeStr}.
RULES:
1. ALWAYS answer the EXACT question asked by the user (e-waste, recycling, time, date, general knowledge, casual chat).
2. Keep ALL responses SHORT: MAXIMUM 2 TO 3 LINES TOTAL.
3. Do NOT use subheadings, bold templates, or long essays. Answer naturally in 2 to 3 short lines.`;

    const messagesPayload = [
      { role: 'system', content: systemPrompt },
      ...(history || []),
      { role: 'user', content: message },
    ];

    const modelsToTry = ['gpt-4o-mini', 'gpt-4o', 'gpt-3.5-turbo'];

    for (const model of modelsToTry) {
      try {
        const openaiRes = await fetch('https://api.openai.com/v1/chat/completions', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${apiKey}`,
          },
          body: JSON.stringify({
            model: model,
            messages: messagesPayload,
            temperature: 0.7,
            max_tokens: 120,
          }),
        });

        if (openaiRes.ok) {
          const data = await openaiRes.json();
          const reply = data.choices[0]?.message?.content;
          if (reply) {
            return NextResponse.json({ reply: reply.trim() });
          }
        }
      } catch (e) {}
    }

    return NextResponse.json({ reply: generateSmartDynamicResponse(message) });
  } catch (error: any) {
    return NextResponse.json({ reply: generateSmartDynamicResponse('') });
  }
}
